### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by fengyunyi** [jiesutd/SUTDAnnotator#1]
Following the steps to use it but the shortcuts don't work. Using python 2.7 on Ubuntu 16.04.

**Comment by jiesutd** [comment]
Hi fenyunyi, is there any notification when you press the shortcut? 
Be sure you need to select some words/characters first then press the shortcut.
Also make sure the shortcut key is belonging to the map shown in right side.

**Comment by fengyunyi** [comment]
Thank you jiesutd. I get it working.
