### ISSUE TITLE
For text classification and Chinese word segmentation job

### ISSUE THREAD

**Issue by SmartAILM** [jiesutd/SUTDAnnotator#2]
Hi @jiesutd , good job for text annotator. Is there any plan for supporting text classification and 
Chinese word segmentation job annotation?

**Comment by jiesutd** [comment]
Hi @SmartAILM, glad to hear from you.
I do not have plan to develop tool for Chinese word segmentation because it seem quite easy, just type space in any text editor. For text classification, I do not plan for this task either.
