### ISSUE TITLE
differences between SUTDAnnotator and SUTDAnnotator-event?

### ISSUE THREAD

**Issue by insomniaCN** [jiesutd/SUTDAnnotator#4]
Hello,
  you mean that SUTDAnnotator-event is an annotator for event, however when I tried with SUTDAnnotator-event.py I found nothing different from SUTDAnnotator.py. So where am I wrong?

**Comment by jiesutd** [comment]
Hi insomniaCN,

Yes, the SUTDAnnotator-event is desinged for event annotation. The interface is same with SUTDAnnotator.py but with more features.  This funtion is still tuned but works well currently. I didn not have time to write readme notes for the event annotation, will try add the notes soon.

Here is a basic use introduction for event annotation:

The most importance feature is that you can give assign number for each event mention. Just select text, press number (i.e. 1, 2,...) and press the mention type shortcut (i.e. a, b,c,...), the system will assign the mention with a label **and a number**.

Let's see a poor example, given a sentence with two events:

> Apple sued Google.  Amazon acquires Whole Foods two days ago.

You want to annotate the two events as tuple formats, like (APPLE, action, Goole) and (Amazon, action, Whole Foods). Then you can use the shortcut and number to distinguish different events by converting this text as : 

> [@Apple#1Subject*] [@sued#1Action*] [@Google#1Objective*].  [@Amazon#2Subject*] [@acquires#2Action*] [@Whole Foods#2Objective*] two days ago.

Here the related mentions are assigned with both label and number, where the number represent the index of events. 

You can use this tool to annotate raw text into above format. For example, if you want to assign "Apple" with label "Subject" and number "1", just select "Apple" and press "1" and press "a" (the shortcut key of label "Subject"). 

It is quite similar with the entity annotation and is also quite efficient.

**Comment by insomniaCN** [comment]
thx for your detailed reply. You can add this reply to README, it looks easy to understand.
